version: '3'

services:
  lambda-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    environment:
      - spring_profile=local
    networks:
      - my-network

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566" # port of to where localstack can be addressed to
    environment:
      - SERVICES=dynamodb # a list of desired services you want to use.
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/private${TMPDIR}:/tmp/localstack"
    networks:
      - my-network
networks:
  my-network: